import { BotProfile } from './types';

export const DEFAULT_PROFILES: Record<string, BotProfile> = {
  nit: {
    id: 'nit',
    name: '岩石型 (Nit)',
    description: '極度保守且規避風險。只玩優質頂級牌，極少詐唬，面對加注容易棄牌。',
    vpip: 0.12,
    pfr: 0.09,
    threeBetFrequency: 0.04,
    aggression: 0.45,
    bluffFrequency: 0.03,
    foldToThreeBet: 0.80,
    continuationBet: 0.50,
    foldToCBet: 0.70,
    checkRaiseFrequency: 0.03,
    riverBluffFrequency: 0.02,
    betSizing: {
      small: 0.33,
      medium: 0.60,
      large: 0.85,
      overbet: 1.10,
    },
  },
  tag: {
    id: 'tag',
    name: '鯊魚型 (TAG)',
    description: '緊兇型風格。手牌選擇謹慎，進池後積極下注施壓，面對強攻能冷靜棄牌。',
    vpip: 0.22,
    pfr: 0.18,
    threeBetFrequency: 0.08,
    aggression: 0.65,
    bluffFrequency: 0.12,
    foldToThreeBet: 0.55,
    continuationBet: 0.65,
    foldToCBet: 0.42,
    checkRaiseFrequency: 0.09,
    riverBluffFrequency: 0.08,
    betSizing: {
      small: 0.33,
      medium: 0.66,
      large: 0.75,
      overbet: 1.25,
    },
  },
  lag: {
    id: 'lag',
    name: '狂放型 (LAG)',
    description: '鬆兇型風格。手牌範圍極廣，積極進攻弱點，頻繁進行 3-Bet 與連續開火施壓。',
    vpip: 0.34,
    pfr: 0.28,
    threeBetFrequency: 0.14,
    aggression: 0.80,
    bluffFrequency: 0.24,
    foldToThreeBet: 0.40,
    continuationBet: 0.75,
    foldToCBet: 0.30,
    checkRaiseFrequency: 0.14,
    riverBluffFrequency: 0.18,
    betSizing: {
      small: 0.33,
      medium: 0.75,
      large: 1.0,
      overbet: 1.50,
    },
  },
  calling_station: {
    id: 'calling_station',
    name: '跟注站 (Calling Station)',
    description: '被動好奇型。喜歡看翻牌並一路用中弱對子跟注到底，極少主動加注或詐唬。',
    vpip: 0.46,
    pfr: 0.08,
    threeBetFrequency: 0.02,
    aggression: 0.25,
    bluffFrequency: 0.04,
    foldToThreeBet: 0.25,
    continuationBet: 0.35,
    foldToCBet: 0.22,
    checkRaiseFrequency: 0.02,
    riverBluffFrequency: 0.03,
    betSizing: {
      small: 0.33,
      medium: 0.50,
      large: 0.66,
      overbet: 1.0,
    },
  },
  maniac: {
    id: 'maniac',
    name: '瘋子型 (Maniac)',
    description: '超高激進度。不斷開火詐唬，超高頻率 3-Bet 與 4-Bet，熱愛超額下注 (Overbet)。',
    vpip: 0.56,
    pfr: 0.44,
    threeBetFrequency: 0.24,
    aggression: 0.92,
    bluffFrequency: 0.38,
    foldToThreeBet: 0.20,
    continuationBet: 0.88,
    foldToCBet: 0.20,
    checkRaiseFrequency: 0.20,
    riverBluffFrequency: 0.30,
    betSizing: {
      small: 0.50,
      medium: 0.85,
      large: 1.25,
      overbet: 2.0,
    },
  },
  balanced: {
    id: 'balanced',
    name: '平衡型 (Balanced)',
    description: '接近 GTO 平衡打法。具備良好的價值與詐唬比例，重視位置優勢與數學勝率。',
    vpip: 0.25,
    pfr: 0.20,
    threeBetFrequency: 0.09,
    aggression: 0.60,
    bluffFrequency: 0.15,
    foldToThreeBet: 0.50,
    continuationBet: 0.62,
    foldToCBet: 0.40,
    checkRaiseFrequency: 0.08,
    riverBluffFrequency: 0.10,
    betSizing: {
      small: 0.33,
      medium: 0.66,
      large: 0.80,
      overbet: 1.33,
    },
  },
};
